name: Docker Image CI

on:
  push:
    branches: [ multiarch ]
  pull_request:
    branches: [ multiarch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build mbed-os-env-cmake Docker image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --output "type=image,push=false" \
          --file mbed-os-env-cmake/Dockerfile \
          --tag pan2048/mbed-os-env-cmake:latest \
          ./mbed-os-env-cmake

    - name: Inspect image
      run: docker buildx imagetools inspect pan2048/mbed-os-env-cmake::latest
