name: Docker Image CI

on:
  push:
    branches: [ multiarch ]
  pull_request:
    branches: [ multiarch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build mbed-os-env-cmake Docker image
      run: docker build . --file mbed-os-env-cmake/Dockerfile --tag pan2048/mbed-os-env-cmake:$(date +%s)
